import csv
import random

def generate_data(num_records):
    data = []
    for i in range(1, num_records + 1):
        house = i
        address = random.choice([ "Biratnagar",
    "Dharan",
    "Itahari",
    "Mechinagar",
    "Urlabari",
    "Inaruwa",
    "Damak",
    "Bhadrapur",
    "Ilam",
    "Biratchowk",
    "Khandbari",
    "Lahan",
    "Bhojpur",
    "Dhankuta",
    "Phidim",
    "Gauradaha",
    "Birtamod",
    "Rajbiraj",
    "Dhulikhel",
    "Janakpur",
    "Malangwa",
    "Hetauda",
    "Tansen",
    "Birgunj",
    "Pokhara",
    "Gaur",
    "Golbazar",
    "Damak",
    "Belbari",
    "Kalaiya",
    "Lalbandi",
    "Kamalamai",
    "Siraha",
    "Dharan",
    "Siddharthanagar",
    "Dhulikhel",
    "Kohalpur",
    "Dharan",
    "Mechinagar",
    "Damak",
    "Kankai",
    "Bhimeshwar",
    "Inaruwa",
    "Kathari",
    "Narayangarh",
    "Koshi",
    "Itahari",
    "Kakarvitta",
    "Dharan",
    "Khadbari",
    "Biratchowk",
    "Lahan",
    "Gurhewa",
    "Chainpur",
    "Urlabari",
    "Dharan",
    "Damak",
    "Bhadrapur",
    "Inaruwa",
    "Biratnagar",
    "Itahari",
    "Urlabari",
    "Dharan",
    "Jaleswar",
    "Mechinagar",
    "Kankai",
    "Gauradaha",
    "Lahan",
    "Itahari",
    "Damak",
    "Tikapur",
    "Dhangadhi",
    "Beldandi",
    "Attariya",
    "Gulariya",
    "Lalbandi",
    "Sauraha",
    "Itahari",
    "Damak",
    "Bhadrapur",
    "Inaruwa",
    "Biratnagar",
    "Dharan",
    "Dhankuta",
    "Phidim",
    "Birtamod",
    "Rajbiraj",
    "Hetauda",
    "Birgunj",
    "Pokhara",
    "Damak",
    "Siraha",
    "Dharan",
    "Siddharthanagar",
    "Dhulikhel",
    "Kohalpur",
    "Nepalganj",
    "Bharatpur",
    "Gaur",
    "Kalaiya",
    "Jaleswar",
    "Itahari",
    "Dharan",
    "Dhankuta",
    "Birtamod",
    "Kankai",
    "Bhadrapur",
    "Phidim",
    "Rajbiraj",
    "Biratnagar",
    "Damak",
    "Itahari",
    "Inaruwa",
    "Lahan",
    "Gauradaha",
    "Mechinagar",
    "Tikapur",
    "Dhangadhi",
    "Beldandi",
    "Attariya",
    "Gulariya",
    "Lalbandi",
    "Sauraha",
    "Itahari",
    "Dharan",
    "Dhankuta",
    "Birtamod",
    "Kankai",
    "Bhadrapur",
    "Phidim",
    "Rajbiraj",
    "Biratnagar",
    "Damak",
    "Itahari",
    "Inaruwa",
    "Lahan",
    "Gauradaha",
    "Mechinagar",
    "Tikapur",
    "Dhangadhi",
    "Beldandi",
    "Attariya",
    "Gulariya",
    "Lalbandi",
    "Sauraha",
    "Itahari",
    "Dharan",
    "Dhankuta",
    "Birtamod",
    "Kankai",
    "Bhadrapur",
    "Phidim",
    "Rajbiraj",
    "Biratnagar",
    "Damak",
    "Itahari",
    "Inaruwa",
    "Lahan",
    "Gauradaha",
    "Mechinagar",
    "Tikapur",
    "Dhangadhi",
    "Beldandi",
    "Attariya",
    "Gulariya",
    "Lalbandi",
    "Sauraha"])
        room = random.randint(2, 6)
        floor = random.randint(1, 3)
        age = random.randint(2, 20)
        price = random.randint(5000, 30000)

        data.append([house, address, room, floor, age, price])

    return data

def save_to_csv(filename, data):
    with open(filename, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["House", "Address", "Room", "Floor", "Age", "Price"])
        writer.writerows(data)

if __name__ == "__main__":
    num_data = 7000
    generated_data = generate_data(num_data)
    save_to_csv("generated_data.csv", generated_data)
    print(f"Successfully generated {num_data} data records and saved to 'generated_data.csv'.")
